version: "3"

services:
  backend:
    container_name: gasshuku-isucon-back
    build:
      context: ..
      dockerfile: dev/Dockerfile
    restart: always
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - db

  db:
    container_name: gasshuku-isucon-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isulibrary
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1024m

volumes:
  db: null
